name: Deploy frontend-lab-7 to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'frontendlab-7-control/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload frontendlab-7-control
        uses: actions/upload-pages-artifact@v3
        with:
          path: './frontendlab-7-control'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
